
//         $date = date("m-d-Y");
//         $time = date("h:i A");
//         $str = 
// "************************************************
// Date of Quote:           " . $date . "
// Time of Quote:           " . $time . "
// Hospital:                " . $hosp_name . "
// Antech ID:               " . $antech_id . "
// CS Rep:                  N/A
// Weight:                  " . $weight . "
// Full Necropsy:           " . $necroCost . "
// Carcass Transport:       " . $shipCost . "
//   Area Code:             " . $area_code . "
//   Transport Miles:       N/A
// Cremation:               " . $cremCost . "
// Full Necropsy Total:     " . $total . "
// ************************************************
// ";

               // file_put_contents('smallquotes.txt',$str,FILE_APPEND);

            

        //     $conn = mysqli_connect('localhost', 'root','12345Melrose', 'antech3');

        //     if($conn){
        //         echo 'Connection:' . mysqli_connect_error();
        //     }
        //     if ($conn->connect_error) {
        //         die("Connection failed: " . $conn->connect_error);
        //     }
        

        //     $tempid = $antech_id;
        //     $sql_insert= "INSERT INTO hospitals (antech_id, name) VALUES ($tempid, $hosp_name)";
        //     $result_insert = mysqli_query($conn, $sql_insert);
        
        //     $sql_quotes= "INSERT INTO quotes (antech_id, total) VALUES ($tempid, $necroCost)";
        //     $result_quotes = mysqli_query($conn, $sql_quotes);
        //     var_dump($result_quotes);
        // }
